name: 'desynpuf'
version: '0.1.0'
config-version: 2

profile: 'desynpuf'

vars:
    desynpuf_database: desynpuf                  # configuration required
    desynpuf_schema: source                      # configuration required
    beneficiary_summary: "{{ source('desynpuf','beneficiary_summary') }}"
    inpatient_claims: "{{ source('desynpuf','inpatient_claims') }}"
    outpatient_claims: "{{ source('desynpuf','outpatient_claims') }}"
    carrier_claims: "{{ source('desynpuf','carrier_claims') }}"
    prescription_drug_events: "{{ source('desynpuf','prescription_drug_events') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  desynpuf:
    +schema: staging

seeds:
  desynpuf:
    +schema: vocabulary
