
{{ config(materialized='view') }}

select
    cast(desynpuf_id as string) as desynpuf_id
,   cast(clm_id as string) as clm_id
,   to_date(clm_from_dt,'YYYYMMDD') as clm_from_dt
,   to_date(clm_thru_dt,'YYYYMMDD') as clm_thru_dt
,   cast(icd9_dgns_cd_1 as string) as icd9_dgns_cd_1
,   cast(icd9_dgns_cd_2 as string) as icd9_dgns_cd_2
,   cast(icd9_dgns_cd_3 as string) as icd9_dgns_cd_3
,   cast(icd9_dgns_cd_4 as string) as icd9_dgns_cd_4
,   cast(icd9_dgns_cd_5 as string) as icd9_dgns_cd_5
,   cast(icd9_dgns_cd_6 as string) as icd9_dgns_cd_6
,   cast(icd9_dgns_cd_7 as string) as icd9_dgns_cd_7
,   cast(icd9_dgns_cd_8 as string) as icd9_dgns_cd_8
,   cast(prf_physn_npi_1 as string) as prf_physn_npi_1
,   cast(prf_physn_npi_2 as string) as prf_physn_npi_2
,   cast(prf_physn_npi_3 as string) as prf_physn_npi_3
,   cast(prf_physn_npi_4 as string) as prf_physn_npi_4
,   cast(prf_physn_npi_5 as string) as prf_physn_npi_5
,   cast(prf_physn_npi_6 as string) as prf_physn_npi_6
,   cast(prf_physn_npi_7 as string) as prf_physn_npi_7
,   cast(prf_physn_npi_8 as string) as prf_physn_npi_8
,   cast(prf_physn_npi_9 as string) as prf_physn_npi_9
,   cast(prf_physn_npi_10 as string) as prf_physn_npi_10
,   cast(prf_physn_npi_11 as string) as prf_physn_npi_11
,   cast(prf_physn_npi_12 as string) as prf_physn_npi_12
,   cast(prf_physn_npi_13 as string) as prf_physn_npi_13
,   cast(tax_num_1 as string) as tax_num_1
,   cast(tax_num_2 as string) as tax_num_2
,   cast(tax_num_3 as string) as tax_num_3
,   cast(tax_num_4 as string) as tax_num_4
,   cast(tax_num_5 as string) as tax_num_5
,   cast(tax_num_6 as string) as tax_num_6
,   cast(tax_num_7 as string) as tax_num_7
,   cast(tax_num_8 as string) as tax_num_8
,   cast(tax_num_9 as string) as tax_num_9
,   cast(tax_num_10 as string) as tax_num_10
,   cast(tax_num_11 as string) as tax_num_11
,   cast(tax_num_12 as string) as tax_num_12
,   cast(tax_num_13 as string) as tax_num_13
,   cast(hcpcs_cd_1 as string) as hcpcs_cd_1
,   cast(hcpcs_cd_2 as string) as hcpcs_cd_2
,   cast(hcpcs_cd_3 as string) as hcpcs_cd_3
,   cast(hcpcs_cd_4 as string) as hcpcs_cd_4
,   cast(hcpcs_cd_5 as string) as hcpcs_cd_5
,   cast(hcpcs_cd_6 as string) as hcpcs_cd_6
,   cast(hcpcs_cd_7 as string) as hcpcs_cd_7
,   cast(hcpcs_cd_8 as string) as hcpcs_cd_8
,   cast(hcpcs_cd_9 as string) as hcpcs_cd_9
,   cast(hcpcs_cd_10 as string) as hcpcs_cd_10
,   cast(hcpcs_cd_11 as string) as hcpcs_cd_11
,   cast(hcpcs_cd_12 as string) as hcpcs_cd_12
,   cast(hcpcs_cd_13 as string) as hcpcs_cd_13
,   cast(line_nch_pmt_amt_1 as number) as line_nch_pmt_amt_1
,   cast(line_nch_pmt_amt_2 as number) as line_nch_pmt_amt_2
,   cast(line_nch_pmt_amt_3 as number) as line_nch_pmt_amt_3
,   cast(line_nch_pmt_amt_4 as number) as line_nch_pmt_amt_4
,   cast(line_nch_pmt_amt_5 as number) as line_nch_pmt_amt_5
,   cast(line_nch_pmt_amt_6 as number) as line_nch_pmt_amt_6
,   cast(line_nch_pmt_amt_7 as number) as line_nch_pmt_amt_7
,   cast(line_nch_pmt_amt_8 as number) as line_nch_pmt_amt_8
,   cast(line_nch_pmt_amt_9 as number) as line_nch_pmt_amt_9
,   cast(line_nch_pmt_amt_10 as number) as line_nch_pmt_amt_10
,   cast(line_nch_pmt_amt_11 as number) as line_nch_pmt_amt_11
,   cast(line_nch_pmt_amt_12 as number) as line_nch_pmt_amt_12
,   cast(line_nch_pmt_amt_13 as number) as line_nch_pmt_amt_13
,   cast(line_bene_ptb_ddctbl_amt_1 as number) as line_bene_ptb_ddctbl_amt_1
,   cast(line_bene_ptb_ddctbl_amt_2 as number) as line_bene_ptb_ddctbl_amt_2
,   cast(line_bene_ptb_ddctbl_amt_3 as number) as line_bene_ptb_ddctbl_amt_3
,   cast(line_bene_ptb_ddctbl_amt_4 as number) as line_bene_ptb_ddctbl_amt_4
,   cast(line_bene_ptb_ddctbl_amt_5 as number) as line_bene_ptb_ddctbl_amt_5
,   cast(line_bene_ptb_ddctbl_amt_6 as number) as line_bene_ptb_ddctbl_amt_6
,   cast(line_bene_ptb_ddctbl_amt_7 as number) as line_bene_ptb_ddctbl_amt_7
,   cast(line_bene_ptb_ddctbl_amt_8 as number) as line_bene_ptb_ddctbl_amt_8
,   cast(line_bene_ptb_ddctbl_amt_9 as number) as line_bene_ptb_ddctbl_amt_9
,   cast(line_bene_ptb_ddctbl_amt_10 as number) as line_bene_ptb_ddctbl_amt_10
,   cast(line_bene_ptb_ddctbl_amt_11 as number) as line_bene_ptb_ddctbl_amt_11
,   cast(line_bene_ptb_ddctbl_amt_12 as number) as line_bene_ptb_ddctbl_amt_12
,   cast(line_bene_ptb_ddctbl_amt_13 as number) as line_bene_ptb_ddctbl_amt_13
,   cast(line_bene_prmry_pyr_pd_amt_1 as number) as line_bene_prmry_pyr_pd_amt_1
,   cast(line_bene_prmry_pyr_pd_amt_2 as number) as line_bene_prmry_pyr_pd_amt_2
,   cast(line_bene_prmry_pyr_pd_amt_3 as number) as line_bene_prmry_pyr_pd_amt_3
,   cast(line_bene_prmry_pyr_pd_amt_4 as number) as line_bene_prmry_pyr_pd_amt_4
,   cast(line_bene_prmry_pyr_pd_amt_5 as number) as line_bene_prmry_pyr_pd_amt_5
,   cast(line_bene_prmry_pyr_pd_amt_6 as number) as line_bene_prmry_pyr_pd_amt_6
,   cast(line_bene_prmry_pyr_pd_amt_7 as number) as line_bene_prmry_pyr_pd_amt_7
,   cast(line_bene_prmry_pyr_pd_amt_8 as number) as line_bene_prmry_pyr_pd_amt_8
,   cast(line_bene_prmry_pyr_pd_amt_9 as number) as line_bene_prmry_pyr_pd_amt_9
,   cast(line_bene_prmry_pyr_pd_amt_10 as number) as line_bene_prmry_pyr_pd_amt_10
,   cast(line_bene_prmry_pyr_pd_amt_11 as number) as line_bene_prmry_pyr_pd_amt_11
,   cast(line_bene_prmry_pyr_pd_amt_12 as number) as line_bene_prmry_pyr_pd_amt_12
,   cast(line_bene_prmry_pyr_pd_amt_13 as number) as line_bene_prmry_pyr_pd_amt_13
,   cast(line_coinsrnc_amt_1 as number) as line_coinsrnc_amt_1
,   cast(line_coinsrnc_amt_2 as number) as line_coinsrnc_amt_2
,   cast(line_coinsrnc_amt_3 as number) as line_coinsrnc_amt_3
,   cast(line_coinsrnc_amt_4 as number) as line_coinsrnc_amt_4
,   cast(line_coinsrnc_amt_5 as number) as line_coinsrnc_amt_5
,   cast(line_coinsrnc_amt_6 as number) as line_coinsrnc_amt_6
,   cast(line_coinsrnc_amt_7 as number) as line_coinsrnc_amt_7
,   cast(line_coinsrnc_amt_8 as number) as line_coinsrnc_amt_8
,   cast(line_coinsrnc_amt_9 as number) as line_coinsrnc_amt_9
,   cast(line_coinsrnc_amt_10 as number) as line_coinsrnc_amt_10
,   cast(line_coinsrnc_amt_11 as number) as line_coinsrnc_amt_11
,   cast(line_coinsrnc_amt_12 as number) as line_coinsrnc_amt_12
,   cast(line_coinsrnc_amt_13 as number) as line_coinsrnc_amt_13
,   cast(line_alowd_chrg_amt_1 as number) as line_alowd_chrg_amt_1
,   cast(line_alowd_chrg_amt_2 as number) as line_alowd_chrg_amt_2
,   cast(line_alowd_chrg_amt_3 as number) as line_alowd_chrg_amt_3
,   cast(line_alowd_chrg_amt_4 as number) as line_alowd_chrg_amt_4
,   cast(line_alowd_chrg_amt_5 as number) as line_alowd_chrg_amt_5
,   cast(line_alowd_chrg_amt_6 as number) as line_alowd_chrg_amt_6
,   cast(line_alowd_chrg_amt_7 as number) as line_alowd_chrg_amt_7
,   cast(line_alowd_chrg_amt_8 as number) as line_alowd_chrg_amt_8
,   cast(line_alowd_chrg_amt_9 as number) as line_alowd_chrg_amt_9
,   cast(line_alowd_chrg_amt_10 as number) as line_alowd_chrg_amt_10
,   cast(line_alowd_chrg_amt_11 as number) as line_alowd_chrg_amt_11
,   cast(line_alowd_chrg_amt_12 as number) as line_alowd_chrg_amt_12
,   cast(line_alowd_chrg_amt_13 as number) as line_alowd_chrg_amt_13
,   cast(line_prcsg_ind_cd_1 as string) as line_prcsg_ind_cd_1
,   cast(line_prcsg_ind_cd_2 as string) as line_prcsg_ind_cd_2
,   cast(line_prcsg_ind_cd_3 as string) as line_prcsg_ind_cd_3
,   cast(line_prcsg_ind_cd_4 as string) as line_prcsg_ind_cd_4
,   cast(line_prcsg_ind_cd_5 as string) as line_prcsg_ind_cd_5
,   cast(line_prcsg_ind_cd_6 as string) as line_prcsg_ind_cd_6
,   cast(line_prcsg_ind_cd_7 as string) as line_prcsg_ind_cd_7
,   cast(line_prcsg_ind_cd_8 as string) as line_prcsg_ind_cd_8
,   cast(line_prcsg_ind_cd_9 as string) as line_prcsg_ind_cd_9
,   cast(line_prcsg_ind_cd_10 as string) as line_prcsg_ind_cd_10
,   cast(line_prcsg_ind_cd_11 as string) as line_prcsg_ind_cd_11
,   cast(line_prcsg_ind_cd_12 as string) as line_prcsg_ind_cd_12
,   cast(line_prcsg_ind_cd_13 as string) as line_prcsg_ind_cd_13
,   cast(line_icd9_dgns_cd_1 as string) as line_icd9_dgns_cd_1
,   cast(line_icd9_dgns_cd_2 as string) as line_icd9_dgns_cd_2
,   cast(line_icd9_dgns_cd_3 as string) as line_icd9_dgns_cd_3
,   cast(line_icd9_dgns_cd_4 as string) as line_icd9_dgns_cd_4
,   cast(line_icd9_dgns_cd_5 as string) as line_icd9_dgns_cd_5
,   cast(line_icd9_dgns_cd_6 as string) as line_icd9_dgns_cd_6
,   cast(line_icd9_dgns_cd_7 as string) as line_icd9_dgns_cd_7
,   cast(line_icd9_dgns_cd_8 as string) as line_icd9_dgns_cd_8
,   cast(line_icd9_dgns_cd_9 as string) as line_icd9_dgns_cd_9
,   cast(line_icd9_dgns_cd_10 as string) as line_icd9_dgns_cd_10
,   cast(line_icd9_dgns_cd_11 as string) as line_icd9_dgns_cd_11
,   cast(line_icd9_dgns_cd_12 as string) as line_icd9_dgns_cd_12
,   cast(line_icd9_dgns_cd_13 as string) as line_icd9_dgns_cd_13
from {{ var('carrier_claims') }}